pub const TokenType = enum {
    AND,
    BANG,
    BANG_EQUAL,
    CLASS,
    COMMA,
    DOT,
    ELSE,
    EOF,
    EQUAL,
    EQUAL_EQUAL,
    ERROR,
    FALSE,
    FOR,
    FUN,
    GREATER,
    GREATER_EQUAL,
    IDENTIFIER,
    IF,
    LEFT_BRACE,
    LEFT_PARENTHESIZE,
    LESS,
    LESS_EQUAL,
    MINUS,
    NULL,
    NUMBER,
    OR,
    PLUS,
    RETURN,
    PRINT,
    RIGHT_BRACE,
    RIGHT_PARENTHESIZE,
    SEMICOLON,
    SLASH,
    STAR,
    STRING,
    SUPER,
    THIS,
    TRUE,
    VAR,
    WHILE,
};

pub const Token = struct {
    tokenType: TokenType,
    start: [*]const u8,
    line: u32,
    length: usize,
    pub fn init(tokenType: TokenType, start: [*]const u8, line: u32, length: usize) Token {
        return Token{
            .tokenType = tokenType,
            .start = start,
            .line = line,
            .length = length,
        };
    }
};
