name: Test

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{matrix.operatingsystems}}

    strategy:
      matrix:
        operatingsystems: [ubuntu-latest, macos-latest, windows-latest] 

    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - run: zig build test
